### ISSUE TITLE
Keyboard is frozen when inputing letters in InputActivity

### ISSUE THREAD

**Issue by rayworks** [passsy/Konduit#8]
<img width="397" alt="screen shot 2018-08-30 at 00 09 58" src="https://user-images.githubusercontent.com/1329281/44800721-af34c180-abe9-11e8-9dd6-461f88241878.png">

The log attached as below:
[log.txt](https://github.com/passsy/Konduit/files/2332887/log.txt)

**Comment by passsy** [comment]
Thanks for the report. What exactly have you done? only typing, long press or just tapped on the EditText?

**Comment by rayworks** [comment]
It seems the issue can be reproduced this way, I keep inputing the words even after the cursor reaches the end of the EditorText. Suddenly, the cursor moves to the front automatically and the above issue occurs.

Device info: 
Nokia 6 with OS 8.1

**Comment by passsy** [comment]
Happened when I was typing pretty fast. Great catch!
